/*
 * Archive
 *
 * The Archive API returns an array of NYT articles for a given month, going back to 1851.  Its response fields are the same as the Article Search API. The Archive API is very useful if you want to build your own database of NYT article metadata. You simply pass the API the year and month and it returns a JSON object with all articles for that month.  The response size can be large (~20mb).  ``` /{year}/{month}.json ```  ## Example Call ``` https://api.nytimes.com/svc/archive/v1/2019/1.json?api-key=yourkey ``` 
 *
 * The version of the OpenAPI document: 2.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Text;
using System.ComponentModel.DataAnnotations;

namespace NYTimes.NET.Models.Archive
{
    /// <summary>
    /// Headline
    /// </summary>
    [DataContract(Name = "Headline")]
    public class Headline : IEquatable<Headline>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="Headline" /> class.
        /// </summary>
        /// <param name="main">main.</param>
        /// <param name="kicker">kicker.</param>
        /// <param name="contentKicker">contentKicker.</param>
        /// <param name="printHeadline">printHeadline.</param>
        /// <param name="name">name.</param>
        /// <param name="seo">seo.</param>
        /// <param name="sub">sub.</param>
        public Headline(string main = default, string kicker = default, string contentKicker = default,
            string printHeadline = default, string name = default, string seo = default, string sub = default)
        {
            this.Main = main;
            this.Kicker = kicker;
            this.ContentKicker = contentKicker;
            this.PrintHeadline = printHeadline;
            this.Name = name;
            this.Seo = seo;
            this.Sub = sub;
        }

        /// <summary>
        /// Gets or Sets Main
        /// </summary>
        [DataMember(Name = "main", EmitDefaultValue = false)]
        public string Main { get; }

        /// <summary>
        /// Gets or Sets Kicker
        /// </summary>
        [DataMember(Name = "kicker", EmitDefaultValue = false)]
        public string Kicker { get; }

        /// <summary>
        /// Gets or Sets ContentKicker
        /// </summary>
        [DataMember(Name = "content_kicker", EmitDefaultValue = false)]
        public string ContentKicker { get; }

        /// <summary>
        /// Gets or Sets PrintHeadline
        /// </summary>
        [DataMember(Name = "print_headline", EmitDefaultValue = false)]
        public string PrintHeadline { get; }

        /// <summary>
        /// Gets or Sets Name
        /// </summary>
        [DataMember(Name = "name", EmitDefaultValue = false)]
        public string Name { get; }

        /// <summary>
        /// Gets or Sets Seo
        /// </summary>
        [DataMember(Name = "seo", EmitDefaultValue = false)]
        public string Seo { get; }

        /// <summary>
        /// Gets or Sets Sub
        /// </summary>
        [DataMember(Name = "sub", EmitDefaultValue = false)]
        public string Sub { get; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class Headline {\n");
            sb.Append("  Main: ").Append(Main).Append('\n');
            sb.Append("  Kicker: ").Append(Kicker).Append('\n');
            sb.Append("  ContentKicker: ").Append(ContentKicker).Append('\n');
            sb.Append("  PrintHeadline: ").Append(PrintHeadline).Append('\n');
            sb.Append("  Name: ").Append(Name).Append('\n');
            sb.Append("  Seo: ").Append(Seo).Append('\n');
            sb.Append("  Sub: ").Append(Sub).Append('\n');
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as Headline);
        }

        /// <summary>
        /// Returns true if Headline instances are equal
        /// </summary>
        /// <param name="input">Instance of Headline to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(Headline input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.Main == input.Main ||
                    (this.Main != null &&
                    this.Main.Equals(input.Main))
                ) && 
                (
                    this.Kicker == input.Kicker ||
                    (this.Kicker != null &&
                    this.Kicker.Equals(input.Kicker))
                ) && 
                (
                    this.ContentKicker == input.ContentKicker ||
                    (this.ContentKicker != null &&
                    this.ContentKicker.Equals(input.ContentKicker))
                ) && 
                (
                    this.PrintHeadline == input.PrintHeadline ||
                    (this.PrintHeadline != null &&
                    this.PrintHeadline.Equals(input.PrintHeadline))
                ) && 
                (
                    this.Name == input.Name ||
                    (this.Name != null &&
                    this.Name.Equals(input.Name))
                ) && 
                (
                    this.Seo == input.Seo ||
                    (this.Seo != null &&
                    this.Seo.Equals(input.Seo))
                ) && 
                (
                    this.Sub == input.Sub ||
                    (this.Sub != null &&
                    this.Sub.Equals(input.Sub))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                var hashCode = 41;
                if (this.Main != null)
                    hashCode = hashCode * 59 + this.Main.GetHashCode();
                if (this.Kicker != null)
                    hashCode = hashCode * 59 + this.Kicker.GetHashCode();
                if (this.ContentKicker != null)
                    hashCode = hashCode * 59 + this.ContentKicker.GetHashCode();
                if (this.PrintHeadline != null)
                    hashCode = hashCode * 59 + this.PrintHeadline.GetHashCode();
                if (this.Name != null)
                    hashCode = hashCode * 59 + this.Name.GetHashCode();
                if (this.Seo != null)
                    hashCode = hashCode * 59 + this.Seo.GetHashCode();
                if (this.Sub != null)
                    hashCode = hashCode * 59 + this.Sub.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        public IEnumerable<ValidationResult> Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
