# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core


trigger:
- main

pool:
  vmImage: ubuntu-latest

variables:
  buildConfiguration: 'Release'
  projectName: 'NYTimes.NET'

steps:
- task: DotNetCoreCLI@2
  displayName: Restore packages
  inputs:
    command: 'restore'
    projects: '$(projectName).sln'
    feedsToUse: 'select'
- task: DotNetCoreCLI@2
  displayName: Build solution
  inputs:
    command: 'build'
    projects: '$(projectName).sln'
    arguments: '--configuration $(buildConfiguration)'
- task: DotNetCoreCLI@2
  displayName: Run unit tests
  inputs:
    command: 'test'
    projects: '$(projectName).Tests/$(projectName).Tests.csproj'
    arguments: '--configuration $(buildConfiguration)'
    testRunTitle: 'Run unit tests'
- task: DotNetCoreCLI@2
  displayName: Generate NuGet Package
  inputs:
    command: 'pack'
    packagesToPack: '$(Build.SourcesDirectory)/$(projectName)/$(projectName).csproj'
    versioningScheme: 'off'
- task: PublishPipelineArtifact@1
  inputs:
    targetPath: '$(Build.ArtifactStagingDirectory)'
    artifact: 'drop'
    publishLocation: 'pipeline'

